### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-belgium#36]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] account_companyweb
- [x] l10n_be_antibiotic_tax
- [x] l10n_be_apb_tax
- [x] l10n_be_eco_tax
- [ ] l10n_be_iso20022_pain https://github.com/OCA/l10n-belgium/pull/48
- [x] l10n_be_mis_reports https://github.com/OCA/l10n-belgium/pull/40

**Comment by yvaucher** [comment]
Added tax modules which appeared on 9.0 branch in the mean time
