### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-belgium#47]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_companyweb
- [ ] l10n_be_antibiotic_tax
- [ ] l10n_be_apb_tax
- [ ] l10n_be_eco_tax
- [ ] l10n_be_iso20022_pain
- [ ] l10n_be_mis_reports
